version: '3.7'

services:
  db:
    image: postgres:11-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"

  rudder:
    image: 454531037350.dkr.ecr.us-east-1.amazonaws.com/rudder-server:latest
    depends_on:
      - db
      - transformer
    entrypoint: sh -c './wait-for db:5432 -- rudder-server'
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - JOBS_DB_HOST=db

  transformer:
    image: 454531037350.dkr.ecr.us-east-1.amazonaws.com/rudder-transformer:latest
    ports:
      - "9091:9090"
    env_file:
      - .env
