name: Notion Sync

on:
  issues:
    types: [opened, edited, milestoned, closed, reopened, assigned, unassigned]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
    - name: Github issues on Notion
      uses: rudderlabs/github-notion@0.0.5-beta
      with:
        token: ${{ secrets.NOTION_BOT_TOKEN }}
        dbID: ${{ secrets.NOTION_ISSUE_DB_ID }}
        pat: ${{ secrets.PAT }}
